### ISSUE TITLE
did you look at other libs that did this already?

### ISSUE THREAD

**Issue by cordoval** [sdboyer/gliph#9]
is imporatnt as this is already in drupal core

**Comment by sdboyer** [comment]
oh, never responded to this. yeah, i did, but the only one i found in php is https://github.com/clue/graph, and i dislike that one because it tries to have one flexigraph that can do everything, and i preferred a (more performant) approach where you build for specific graph types and behaviors, which allows greater optimization.

**Comment by lyrixx** [comment]
BTW, there is code living in [this repository](https://github.com/doctrine/orientdb-odm#utilities) that may help you with #6

**Comment by sdboyer** [comment]
i'll have a look, thanks.

the primary blocker on #6 is just that i haven't implemented a weighted graph yet. once that data is available, dijstrka's shortest path isn't particularly difficult to implement.

some of the changes in the `new-generator` branch will help specify the pattern by which a weighted graph can be expressed, as they make it clear how additional edge data is reported through the enumerators.
